routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () { return view('welcome'); })->name('index');

Route::resource('facility','FacilityController');

Route::resource('room','RoomController');

Route::resource('room-type','RoomTypeController');

Route::resource('season','SeasonController');

Route::resource('price','PriceController');

Route::resource('user','AccountController');

Route::resource('report','ReportController');

Route::resource('reservation','ReservationController');

Route::post('login','AccountController@login')->name("login.submit");

Route::get('login','AccountController@showLogin')->name('login');

Route::post('logout','AccountController@logout')->name('logout');

Route::post('register','AccountController@createGuest')->name("guest.create.submit");

Route::get('register', function () {
	return view('register');
})->name('register');

Route::get('forgot', function () {
	return view('forgot');
})->name('forgot');

Route::post('forgot', 'AccountController@validateForgotPassword')->name('forgot.submit');

Route::post('reset', 'AccountController@resetPassword')->name('reset.submit');

Route::get('account/profile', 'AccountController@show')->name('account.profile');

Route::get('account/profile/edit', 'AccountController@edit')->name('account.profile.edit');

Route::get('account/reservation', 'ReservationController@show')->name('reservation.show');

Route::get('account/reservation/cancel/{reservation}', 'ReservationController@cancelReservation')->name('reservation.cancel');

Route::get('account/reservation/print/{reservation}', 'ReservationController@printReservation')->name('reservation.print');

Route::get('account/history', 'ReservationController@showHistory')->name('reservation.history');

Route::get('account/history/{reservation}', 'ReservationController@showHistoryDetail')->name('reservation.history.detail');

Route::get('account', function () {
	return redirect()->route('account.profile');
})->name('account.index');

Route::get('showcase/{name}', 'SideController@showRoomDetail')->name('side.showcase');

Route::get('orderRoom', 'SideController@createOrder')->name('side.room.order');

Route::get('searchRoom', 'SideController@showSearchRoom')->name('side.room.search');

Route::post('confirmation', 'SideController@showConfirmRoom')->name('side.room.confirm');

Route::post('payment', 'SideController@showPayment')->name('side.payment');

Route::post('storePayment', 'SideController@storePayment')->name('side.payment.store');

Route::post('getSearchRoom', 'SideController@searchRoomReservation')->name('side.room.getsearch');

Route::post('getYearIncome', 'ReportController@getYearIncome')->name('report.getYearIncome');

Route::post('getNewCustomer', 'ReportController@getNewCustomer')->name('report.getNewCustomer');

Route::post('getTopFive', 'ReportController@getTopFive')->name('report.getTopFive');

Route::post('getMonthIncome', 'ReportController@getMonthIncome')->name('report.getMonthIncome');

Route::post('getGuestType', 'ReportController@getGuestType')->name('report.getGuestType');

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

resources/views/user/create.blade.php
@extends('layouts.menu')

@section('title', 'Tambah User Baru')

@section('header', 'User')

@section('back', route('user.index'))
	
@section('content')
	<form method="POST" action="{{ route('user.store') }}">
		@csrf
		@include('user.form')
	</form>
@endsection

resources/views/user/edit.blade.php
@extends('layouts.menu')

@section('title')
	Ubah User #{{ $user->id }}
@endsection

@section('header', 'User')

@section('back', route('user.index'))

@section('value_name', $user->name)

@section('value_email', $user->email)

@section('value_role', $user->role)

@section('value_status', $user->status)

@section('value_noid', $user->identity_number)

@section('value_tel', $user->telephone)

@section('value_branch', $user->branch_id)

@section('value_addr', $user->address)
	
@section('content')
	<form method="POST" action="{{ route('user.update', $user->id) }}">
		@method('PUT')
		@csrf
		@include('user.form')
	</form>
@endsection

resources/views/user/form.blade.php
<div class="p-4 rounded bg-light">
	<h3>@yield('title')</h3>
	<div class="row">
		<div class="form-group col-lg-6">
			<label for="username">Nama</label>
			<input class="form-control" id="username" name="username" maxlength="10" placeholder="Maksimal 10 karakter" 
				@hasSection('value_name')
					value="@yield('value_name')"
				@endif
			>
		</div>
		<div class="form-group col-lg-6">
			<label for="email">Email</label>
			<input class="form-control" id="email" name="email" type="email" maxlength="30" 
				@hasSection('value_email')
					value=@yield('value_email')
				@endif
			>
		</div>
	</div>
	<div class="row">
		<div class="form-group col-lg-6">
			<label for="password">Password</label>
			<input class="form-control" id="password" name="password" type="password" maxlength="15" placeholder="Kombinasi angka, huruf dan karakter khusus">
		</div>
		<div class="form-group col-lg-6">
			<label for="re-password">Konfirmasi Password</label>
			<input class="form-control" id="re-password" name="password_confirmation" type="password" maxlength="30" placeholder="Masukkan kembali password">
		</div>
	</div>
	<div class="row">
		<div class="form-group col-lg-8">
			<label for="role">Role</label>
			<select class="form-control" id="role" name="role">
				@foreach($roles as $role)
					@hasSection('value_role')
						@if($user->role == $role)
							<option value="{{ $role }}" selected="true">{{ $role }}</option>
						@else
							<option value="{{ $role }}">{{ $role }}</option>
						@endif
					@else
						<option value="{{ $role }}">{{ $role }}</option>
					@endif
				@endforeach
			</select>
		</div>
		<div class="form-group col-lg-4">
			<label for="user_status">Status</label>
			<select class="form-control" id="user_status" name="user_status"
				@hasSection('value_status')
					value=@yield('value_status')
				@endif>
				<option value="Active">Active</option>
				<option value="inactive">Inactive</option>
			</select>
		</div>
	</div>
	<div class="row">
		<div class="form-group col-lg-4">
			<label for="identity_number">No. Identitas</label>
			<input class="form-control" type="number" id="identity_number" name="identity_number" maxlength="16" placeholder="Maksimal 16 angka" 
				@hasSection('value_noid')
					value=@yield('value_noid')
				@endif
			>
		</div>
		<div class="form-group col-lg-4">
			<label for="user_tel">No. Telepon</label>
			<input class="form-control" id="user_tel" type="tel" name="user_tel" maxlength="15" placeholder="Maksimal 15 digit" 
				@hasSection('value_tel')
					value=@yield('value_tel')
				@endif
			>
		</div>
		<div class="form-group col-lg-4">
			<label for="branch_id">Branch</label>
			<!-- <input class="form-control" id="branch_id" type="number" name="branch_id" min="1" 
				@hasSection('value_branch')
					value=@yield('value_branch')
				@endif
			> -->
			<select class="form-control" id="branch_id" name="branch_id" >
				@foreach($branches as $branch)
					@hasSection('value_branch')
						@if($user->branch_id == $branch->id)
							<option value="{{ $branch->id }}" selected="true">{{ $branch->name }}</option>
						@else
							<option value="{{ $branch->id }}">{{ $branch->name }}</option>
						@endif
					@else
						<option value="{{ $branch->id }}">{{ $branch->name }}</option>
					@endif
				@endforeach
			</select>
		</div>
	</div>
	<div class="form-group">
		<label for="address">Alamat</label>
		<textarea class="form-control" id="address" name="address" maxlength="100" placeholder="Maksimal 100 karakter">@hasSection('value_addr')@yield('value_addr')@endif</textarea>
	</div>
	<input type="submit" class="btn btn-success" value="Unggah">
	<input type="reset" class="btn btn-secondary" value="Reset">
</div>

resources/views/user/index.blade.php
@extends('layouts.menu')

@section('title', 'Daftar User')

@section('header', 'User')

@section('create', route('user.create'))

@section('content')
	<div class="mb-3 form-inline">
		<div class="form-group mr-2">
			<input class="form-control searchClue" type="text">
		</div>
		<button class="btn btn-primary" onclick="search(1);"> Search </button>
	</div>
	<table class="table table-sm table-striped table-bordered table-dark text-center">
		<thead class="thead-light">
			<tr>
				<th scope="col" class="align-middle">#</th>
				<th scope="col" class="align-middle">Nama</th>
				<th scope="col" class="align-middle">Role</th>
				<th scope="col" class="align-middle">No. ID</th>
				<th scope="col" class="align-middle">No. Telepon</th>
				<th scope="col" class="align-middle">Alamat</th>
				<th scope="col" class="align-middle">No. Branch</th>
				<th scope="col" class="align-middle">Aksi</th>
			</tr>
		</thead>
		<tbody class="implementSearch">
			@foreach($users as $user)
				<tr>
					<th scope="row" class="align-middle" rowspan="2">{{ $user->id }}</th>
					<td class="align-middle search" name="{{ $user->name }}">{{ $user->name }}</td>
					<td class="align-middle search" name="{{ $user->role }}">{{ $user->role }}</td>
					<td class="align-middle" rowspan="2">{{ $user->identity_number }}</td>
					@if(empty($user->telephone))
						<td class="align-middle" rowspan="2">-</td>
					@else
						<td class="align-middle" rowspan="2">{{ $user->telephone }}</td>
					@endif
					@if(empty($user->address))
						<td class="align-middle" rowspan="2">-</td>
					@else
						<td class="align-middle" rowspan="2">{{ $user->address }}</td>
					@endempty
					@if(empty($user->branch_id))
						<td class="align-middle" rowspan="2">-</td>
					@else
						<td class="align-middle" rowspan="2">@php echo is_null($user->branch_id) ? 0 : $branch[$user->branch_id]; @endphp</td>
					@endif
					<td class="align-middle" rowspan="2">
						<a class="btn btn-info btn-sm my-1" href="{{ route('user.edit', $user->id) }}" role="button">Ubah</a>
						<form method="POST" action="{{ route('user.destroy', $user->id) }}">
							@method('DELETE')
							@csrf
							<input type="submit" class="btn btn-danger btn-sm my-1" value="Hapus">
						</form>
					</td>
				</tr>
				<tr>
					<td class="align-middle">{{ $user->email }}</td>
					<td class="align-middle">{{ $user->status }}</td>
				</tr>
			@endforeach
		</tbody>
	</table>
@endsection