routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () { return view('welcome'); })->name('index');

Route::resource('facility','FacilityController');

Route::resource('room','RoomController');

Route::resource('room-type','RoomTypeController');

Route::resource('season','SeasonController');

Route::resource('price','PriceController');

Route::resource('user','AccountController');

Route::resource('report','ReportController');

Route::resource('reservation','ReservationController');

Route::post('login','AccountController@login')->name("login.submit");

Route::get('login','AccountController@showLogin')->name('login');

Route::post('logout','AccountController@logout')->name('logout');

Route::post('register','AccountController@createGuest')->name("guest.create.submit");

Route::get('register', function () {
	return view('register');
})->name('register');

Route::get('forgot', function () {
	return view('forgot');
})->name('forgot');

Route::post('forgot', 'AccountController@validateForgotPassword')->name('forgot.submit');

Route::post('reset', 'AccountController@resetPassword')->name('reset.submit');

Route::get('account/profile', 'AccountController@show')->name('account.profile');

Route::get('account/profile/edit', 'AccountController@edit')->name('account.profile.edit');

Route::get('account/reservation', 'ReservationController@show')->name('reservation.show');

Route::get('account/reservation/cancel/{reservation}', 'ReservationController@cancelReservation')->name('reservation.cancel');

Route::get('account/reservation/print/{reservation}', 'ReservationController@printReservation')->name('reservation.print');

Route::get('account/history', 'ReservationController@showHistory')->name('reservation.history');

Route::get('account/history/{reservation}', 'ReservationController@showHistoryDetail')->name('reservation.history.detail');

Route::get('account', function () {
	return redirect()->route('account.profile');
})->name('account.index');

Route::get('showcase/{name}', 'SideController@showRoomDetail')->name('side.showcase');

Route::get('orderRoom', 'SideController@createOrder')->name('side.room.order');

Route::get('searchRoom', 'SideController@showSearchRoom')->name('side.room.search');

Route::post('confirmation', 'SideController@showConfirmRoom')->name('side.room.confirm');

Route::post('payment', 'SideController@showPayment')->name('side.payment');

Route::post('storePayment', 'SideController@storePayment')->name('side.payment.store');

Route::post('getSearchRoom', 'SideController@searchRoomReservation')->name('side.room.getsearch');

Route::post('getYearIncome', 'ReportController@getYearIncome')->name('report.getYearIncome');

Route::post('getNewCustomer', 'ReportController@getNewCustomer')->name('report.getNewCustomer');

Route::post('getTopFive', 'ReportController@getTopFive')->name('report.getTopFive');

Route::post('getMonthIncome', 'ReportController@getMonthIncome')->name('report.getMonthIncome');

Route::post('getGuestType', 'ReportController@getGuestType')->name('report.getGuestType');

app/Facility.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Facility extends Model
{
    protected $table = 'facility';
    protected $primaryKey = 'id';
    public $timestamps = false;

    protected $fillable = [
        'name', 'price_idr', 'quantity','status',
    ];
}

app/Http/Controllers/FacilityController.php
<?php

namespace App\Http\Controllers;

use App\Facility;
use Illuminate\Http\Request;

class FacilityController extends Controller
{
    public function __construct(){
        $this->middleware('auth');       
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if (session()->get('user_role')[0] == 'Guest') {
            return redirect()->route('index');
        }

        $facilities = Facility::all();
        return view('facility.index', compact('facilities'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('facility.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        request()->validate([
            'name' => 'required|max:50',
            'price_idr' => 'required|int|min:0',
            'quantity' => 'required|int|min:0',
            'status' => 'required',
        ]);
        Facility::create($request->all());
        return redirect()->route('facility.index')->with('success', 'Fasilitas '.$request->get('name').' berhasil ditambahkan');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Facility  $facility
     * @return \Illuminate\Http\Response
     */
    public function show(Facility $facility)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Facility  $facility
     * @return \Illuminate\Http\Response
     */
    public function edit(Facility $facility)
    {
        return view('facility.edit', ['facility' => $facility]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Facility  $facility
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Facility $facility)
    {
        request()->validate([
            'name' => 'required|max:50',
            'price_idr' => 'required|int|min:0',
            'quantity' => 'required|int|min:0',
            'status' => 'required',
        ]);
        $facility->update($request->all());
        return redirect()->route('facility.index')->with('success', 'Fasilitas #'.$facility->id.' berhasil diubah');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Facility  $facility
     * @return \Illuminate\Http\Response
     */
    public function destroy(Facility $facility)
    {
        try {
            $facility->delete();
            return redirect()->route('facility.index')->with('success', 'Fasilitas #'.$facility->id.' : '.$facility->name.' berhasil dihapus');
        }
        catch (QueryException $e) {
            return redirect()->route('facility.index')->withErrors('Data Fasilitas #'.$facility->id.' masih tersambung dengan data lainnya.');
        }
    }
}

resources/views/facility/create.blade.php
@extends('layouts.menu')

@section('title', 'Tambah Fasilitas Baru')

@section('header', 'Fasilitas')

@section('back', route('facility.index'))
	
@section('content')
	<form method="POST" action="{{ route('facility.store') }}">
		@csrf
		@include('facility.form')
	</form>
@endsection

resources/views/facility/edit.blade.php
@extends('layouts.menu')

@section('title')
	Ubah Fasilitas #{{ $facility->id }}
@endsection

@section('header', 'Fasilitas')

@section('back', route('facility.index'))

@section('value_name', $facility->name)

@section('value_price')
	@if(empty($facility->price_idr))
		"0"
	@else
		{{ $facility->price_idr }}
	@endif
@endsection

@section('value_qty')
	@if(empty($facility->quantity))
		"0"
	@else
		{{ $facility->quantity }}
	@endif
@endsection

@section('value_status', $facility->status)
	
@section('content')
	<form method="POST" action="{{ route('facility.update', $facility->id) }}">
		@method('PUT')
		@csrf
		@include('facility.form')
	</form>
@endsection

resources/views/facility/form.blade.php
<div class="p-4 rounded bg-light">
	<h3>@yield('title')</h3>
	<div class="form-group">
		<label for="fac_name">Nama Fasilitas</label>
		<input class="form-control" id="fac_name" type="text" name="name" maxlength="50" 
			@hasSection('value_name')
				value="@yield('value_name')"
			@endif
		>
	</div>
	<div class="row">
		<div class="form-group col-md-7">
			<label for="fac_price">Harga (Rp.)</label>
			<input class="form-control" id="fac_price" type="number" name="price_idr" min="0" step="1000" 
				@hasSection('value_price')
					value=@yield('value_price')
				@endif
			>
		</div>
		<div class="form-group col-md-5">
			<label for="fac_qty">Kuantitas</label>
			<input class="form-control" id="fac_qty" type="number" name="quantity" min="0" 
				@hasSection('value_qty')
					value=@yield('value_qty')
				@endif
			>
		</div>
	</div>
	<div class="form-group">
		<label for="fac_status">Status</label>
		<!-- <input class="form-control" id="fac_status" type="text" name="status" 
			@hasSection('value_status')
				value="@yield('value_status')"
			@endif
		> -->
		<select class="form-control" id="fac_status" type="text" name="status" @hasSection('value_status')
				value="@yield('value_status')"
			@endif>
			
			<option value="Inactive" @hasSection('value_status')
				 	@if ( $facility->status == "Inactive" ) selected @endIf
				 @endif>
				Inactive
			</option>
			<option value="Active"  @hasSection('value_status')
					@if ( $facility->status == "Active" ) selected @endIf
				@endIf>
				Active
			</option>
		</select>
	</div>
	<input type="submit" class="btn btn-success" value="Unggah">
	<input type="reset" class="btn btn-secondary" value="Reset">
</div>

resources/views/facility/index.blade.php
@extends('layouts.menu')

@section('title', 'Daftar Fasilitas')

@section('header', 'Fasilitas')

@section('create', route('facility.create'))

@section('content')
	<table class="table table-sm table-striped table-bordered table-dark text-center">
		<thead class="thead-light">
			<tr>
				<th scope="col">#</th>
				<th scope="col">Nama Fasilitas</th>
				<th scope="col">Kuantitas</th>
				<th scope="col">Harga</th>
				<th scope="col">Status</th>
				<th scope="col">Aksi</th>
			</tr>
		</thead>
		<tbody>
			@foreach($facilities as $facility)
				<tr>
					<th scope="row" class="align-middle">{{ $facility->id }}</th>
					<td class="align-middle">{{ $facility->name }}</td>
					<td class="align-middle">{{ $facility->quantity }}</td>
					@if ($facility->price_idr == 0)
						<td class="align-middle">-</td>
					@else
						<td class="align-middle">Rp. {{ number_format($facility->price_idr,0,",",".") }}</td>
					@endif
					<td class="align-middle">{{ $facility->status }}</td>
					<td>
						<a class="btn btn-info btn-sm my-1" href="{{ route('facility.edit', $facility->id) }}" role="button">Ubah</a>
						<form method="POST" action="{{ route('facility.destroy', $facility->id) }}">
							@method('DELETE')
							@csrf
							<input type="submit" class="btn btn-danger btn-sm my-1" value="Hapus">
						</form>
					</td>
				</tr>
			@endforeach
		</tbody>
	</table>
@endsection