routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () { return view('welcome'); })->name('index');

Route::resource('facility','FacilityController');

Route::resource('room','RoomController');

Route::resource('room-type','RoomTypeController');

Route::resource('season','SeasonController');

Route::resource('price','PriceController');

Route::resource('user','AccountController');

Route::resource('report','ReportController');

Route::resource('reservation','ReservationController');

Route::post('login','AccountController@login')->name("login.submit");

Route::get('login','AccountController@showLogin')->name('login');

Route::post('logout','AccountController@logout')->name('logout');

Route::post('register','AccountController@createGuest')->name("guest.create.submit");

Route::get('register', function () {
	return view('register');
})->name('register');

Route::get('forgot', function () {
	return view('forgot');
})->name('forgot');

Route::post('forgot', 'AccountController@validateForgotPassword')->name('forgot.submit');

Route::post('reset', 'AccountController@resetPassword')->name('reset.submit');

Route::get('account/profile', 'AccountController@show')->name('account.profile');

Route::get('account/profile/edit', 'AccountController@edit')->name('account.profile.edit');

Route::get('account/reservation', 'ReservationController@show')->name('reservation.show');

Route::get('account/reservation/cancel/{reservation}', 'ReservationController@cancelReservation')->name('reservation.cancel');

Route::get('account/reservation/print/{reservation}', 'ReservationController@printReservation')->name('reservation.print');

Route::get('account/history', 'ReservationController@showHistory')->name('reservation.history');

Route::get('account/history/{reservation}', 'ReservationController@showHistoryDetail')->name('reservation.history.detail');

Route::get('account', function () {
	return redirect()->route('account.profile');
})->name('account.index');

Route::get('showcase/{name}', 'SideController@showRoomDetail')->name('side.showcase');

Route::get('orderRoom', 'SideController@createOrder')->name('side.room.order');

Route::get('searchRoom', 'SideController@showSearchRoom')->name('side.room.search');

Route::post('confirmation', 'SideController@showConfirmRoom')->name('side.room.confirm');

Route::post('payment', 'SideController@showPayment')->name('side.payment');

Route::post('storePayment', 'SideController@storePayment')->name('side.payment.store');

Route::post('getSearchRoom', 'SideController@searchRoomReservation')->name('side.room.getsearch');

Route::post('getYearIncome', 'ReportController@getYearIncome')->name('report.getYearIncome');

Route::post('getNewCustomer', 'ReportController@getNewCustomer')->name('report.getNewCustomer');

Route::post('getTopFive', 'ReportController@getTopFive')->name('report.getTopFive');

Route::post('getMonthIncome', 'ReportController@getMonthIncome')->name('report.getMonthIncome');

Route::post('getGuestType', 'ReportController@getGuestType')->name('report.getGuestType');

app/Http/Controllers/RoomTypeController.php
<?php

namespace App\Http\Controllers;

use App\RoomType;
use Illuminate\Http\Request;

class RoomTypeController extends Controller
{
    public function __construct(){
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if (session()->get('user_role')[0] == 'Guest') {
            return redirect()->route('index');;
        }
        $roomTypes = RoomType::all();
        return view('room-type.index', compact('roomTypes'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('room-type.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        request()->validate([
            'type_name' => 'required',
            'type_code' => 'required',
            'type_cap' => 'required|int|min:1|max:3',
            'type_price' => 'required|int|min:1',
            'type_desc' => 'required',
        ]);

        $typeName = $request->type_name;
        $typeCode = $request->type_code;
        RoomType::create([
            'capacity' => $request->get('type_cap'),
            'code' => strtoupper($request->get('type_code')),
            'description' => $request->get('type_desc'),
            'name' => $request->get('type_name'),
            'status' => 'Active',
            'price_idr' => $request->get('type_price'),
        ]);
        return redirect()->route('room-type.index')->with('success', "Jenis Kamar ".$typeName." (".$typeCode.") berhasil ditambahkan");
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\RoomType  $roomType
     * @return \Illuminate\Http\Response
     */
    public function show(RoomType $roomType)
    {

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\RoomType  $roomType
     * @return \Illuminate\Http\Response
     */
    public function edit(RoomType $roomType)
    {
        return view('room-type.edit', ['roomType' => $roomType]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\RoomType  $roomType
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, RoomType $roomType)
    {
        request()->validate([
            'type_name' => 'required',
            'type_code' => 'required',
            'type_cap' => 'required|int|min:1|max:3',
            'type_price' => 'required|int|min:1',
            'type_desc' => 'required',
        ]);

        $roomType->capacity = $request->get('type_cap');
        $roomType->code = strtoupper($request->get('type_code'));
        $roomType->description = $request->get('type_desc');
        $roomType->name = $request->get('type_name');
        $roomType->price_idr = $request->get('type_price');

        $roomType->save();
        return redirect()->route('room-type.index')->with('success', 'Jenis Kamar '.$roomType->name.' ('.$roomType->code.') berhasil diubah');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\RoomType  $roomType
     * @return \Illuminate\Http\Response
     */
    public function destroy(RoomType $roomType)
    {
        try {
            $roomType->delete();
            return redirect()->route('room-type.index')->with('success', 'Jenis Kamar '.$roomType->name.' ('.$roomType->code.') berhasil dihapus');
        }
        catch (QueryException $e) {
            return redirect()->route('room-type.index')->withErrors('Data Jenis Kamar '.$roomType->name.' ('.$roomType->code.') masih tersambung dengan data lainnya.');
        }
    }
}

resources/views/room-type/create.blade.php
@extends('layouts.menu')

@section('title', 'Tambah Jenis Kamar Baru')

@section('header', 'Jenis Kamar')

@section('back', route('room-type.index'))
	
@section('content')
	<form method="POST" action="{{ route('room-type.store') }}">
		@csrf
		@include('room-type.form')
	</form>
@endsection

resources/views/room-type/edit.blade.php
@extends('layouts.menu')

@section('title')
	Ubah Jenis Kamar {{ $roomType->name }} ({{ $roomType->code }})
@endsection

@section('header', 'Jenis Kamar')

@section('back', route('room-type.index'))

@section('value_name', $roomType->name)

@section('value_code', $roomType->code)

@section('value_price', $roomType->price_idr)

@section('value_cap', $roomType->capacity)

@section('value_desc', $roomType->description)
	
@section('content')
	<form method="POST" action="{{ route('room-type.update', $roomType->id) }}">
		@method('PUT')
		@csrf
		@include('room-type.form')
	</form>
@endsection

resources/views/room-type/form.blade.php
<div class="p-4 rounded bg-light">
	<h3>@yield('title')</h3>
	<div class="row">
		<div class="form-group col-lg-9">
			<label for="type_name">Nama Jenis Kamar</label>
			<input class="form-control" id="type_name" name="type_name" maxlength="25" placeholder="Maksimal 25 huruf" 
				@hasSection('value_name')
					value="@yield('value_name')"
				@endif
			>
		</div>
		<div class="form-group col-lg-3">
			<label for="type_code">Kode Jenis Kamar</label>
			<input class="form-control" id="type_code" name="type_code" maxlength="2" placeholder="Maksimal 2 huruf" 
				@hasSection('value_code')
					value=@yield('value_code')
				@endif
			>
		</div>
	</div>
	<div class="row">
		<div class="form-group col-lg-6">
			<label for="type_price">Harga Jenis Kamar (Rp.)</label>
			<input class="form-control" id="type_price" name="type_price" min="1"
				@hasSection('value_price')
					value=@yield('value_price')
				@endif
			>
		</div>
		<div class="form-group col-lg-6">
			<label for="type_cap">Kapasitas Jenis Kamar</label>
			<input class="form-control" id="type_cap" type="number" name="type_cap" min="1" max="3" placeholder="1 - 3" 
				@hasSection('value_cap')
					value=@yield('value_cap')
				@endif
			>
		</div>
	</div>
	<div class="form-group">
		<label for="type_desc">Deskripsi Jenis Kamar</label>
		<textarea class="form-control" id="type_desc" type="text" name="type_desc" maxlength="100" placeholder="Maksimal 100 huruf">@hasSection('value_desc')@yield('value_desc')@endif</textarea>
	</div>
	<input type="submit" class="btn btn-success" value="Unggah">
	<input type="reset" class="btn btn-secondary" value="Reset">
</div>

resources/views/room-type/index.blade.php
@extends('layouts.menu')

@section('title', 'Daftar Jenis Kamar')

@section('header', 'Jenis Kamar')

@section('create', route('room-type.create'))

@section('content')
	<table class="table table-sm table-striped table-bordered table-dark text-center">
		<thead class="thead-light">
			<tr>
				<th scope="col">Kode dan Nama</th>
				<th scope="col">Status</th>
				<th scope="col">Deskripsi</th>
				<th scope="col">Kapasitas</th>
				<th scope="col">Aksi</th>
			</tr>
		</thead>
		<tbody>
			@foreach($roomTypes as $roomType)
				<tr>
					<th scope="row" class="align-middle">{{ $roomType->code }}</th>
					@if(empty($roomType->status))
						<td class="align-middle" rowspan="2">-</td>
					@else
						<td class="align-middle" rowspan="2">{{ $roomType->status }}</td>
					@endif
					<td class="align-middle">{{ $roomType->description }}</td>
					<td class="align-middle" rowspan="2">{{ $roomType->capacity }} orang</td>
					<td class="align-middle" rowspan="2">
						<a class="btn btn-info btn-sm my-1" href="{{ route('room-type.edit', $roomType->id) }}" role="button">Ubah</a>
						<form method="POST" action="{{ route('room-type.destroy', $roomType->id) }}">
							@method('DELETE')
							@csrf
							<input type="submit" class="btn btn-danger btn-sm my-1" value="Hapus">
						</form>
					</td>
				</tr>
				<tr>
					<th scope="row" class="align-middle">{{ $roomType->name }}</th>
					<td class="align-middle">Rp. {{ number_format($roomType->price_idr,0,",",".") }}</td>
				</tr>
			@endforeach
		</tbody>
	</table>
@endsection