routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () { return view('welcome'); })->name('index');

Route::resource('facility','FacilityController');

Route::resource('room','RoomController');

Route::resource('room-type','RoomTypeController');

Route::resource('season','SeasonController');

Route::resource('price','PriceController');

Route::resource('user','AccountController');

Route::resource('report','ReportController');

Route::resource('reservation','ReservationController');

Route::post('login','AccountController@login')->name("login.submit");

Route::get('login','AccountController@showLogin')->name('login');

Route::post('logout','AccountController@logout')->name('logout');

Route::post('register','AccountController@createGuest')->name("guest.create.submit");

Route::get('register', function () {
	return view('register');
})->name('register');

Route::get('forgot', function () {
	return view('forgot');
})->name('forgot');

Route::post('forgot', 'AccountController@validateForgotPassword')->name('forgot.submit');

Route::post('reset', 'AccountController@resetPassword')->name('reset.submit');

Route::get('account/profile', 'AccountController@show')->name('account.profile');

Route::get('account/profile/edit', 'AccountController@edit')->name('account.profile.edit');

Route::get('account/reservation', 'ReservationController@show')->name('reservation.show');

Route::get('account/reservation/cancel/{reservation}', 'ReservationController@cancelReservation')->name('reservation.cancel');

Route::get('account/reservation/print/{reservation}', 'ReservationController@printReservation')->name('reservation.print');

Route::get('account/history', 'ReservationController@showHistory')->name('reservation.history');

Route::get('account/history/{reservation}', 'ReservationController@showHistoryDetail')->name('reservation.history.detail');

Route::get('account', function () {
	return redirect()->route('account.profile');
})->name('account.index');

Route::get('showcase/{name}', 'SideController@showRoomDetail')->name('side.showcase');

Route::get('orderRoom', 'SideController@createOrder')->name('side.room.order');

Route::get('searchRoom', 'SideController@showSearchRoom')->name('side.room.search');

Route::post('confirmation', 'SideController@showConfirmRoom')->name('side.room.confirm');

Route::post('payment', 'SideController@showPayment')->name('side.payment');

Route::post('storePayment', 'SideController@storePayment')->name('side.payment.store');

Route::post('getSearchRoom', 'SideController@searchRoomReservation')->name('side.room.getsearch');

Route::post('getYearIncome', 'ReportController@getYearIncome')->name('report.getYearIncome');

Route::post('getNewCustomer', 'ReportController@getNewCustomer')->name('report.getNewCustomer');

Route::post('getTopFive', 'ReportController@getTopFive')->name('report.getTopFive');

Route::post('getMonthIncome', 'ReportController@getMonthIncome')->name('report.getMonthIncome');

Route::post('getGuestType', 'ReportController@getGuestType')->name('report.getGuestType');

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
	<head>
		<title>{{ config('app.name') }} - @yield('title')</title>
		@include('style')
    </head>
    <body>
    	@include('navbar')
        <div class="container">
        	@section('sidebar')
				<h1>This is the master sidebar.</h1>
			@show
			@yield('content')
		</div>
	</body>
</html>

resources/views/layouts/auth-form.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
	<head>
		<title>{{ config('app.name') }} - @yield('title')</title>
		@include('style')
    </head>
    <body background="{{ URL::asset('img/login.jpg') }}">
    	@include('navbar')
        <div class="container">
        	<div class="card @yield('style') mx-auto my-5">
        		<div class="card-header text-center">@yield('card-header')</div>
        		<div class="card-body">@yield('card-body')</div>
        		@hasSection('card-footer')
        		<div class="card-footer">
        			<div class="text-center">
        				@yield('card-footer')
        			</div>
        		</div>
        		@endif
			</div>
		</div>
		{{-- @include('footer') --}}
	</body>
</html>

resources/views/layouts/menu-frame.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
	<head>
		<title>@yield('title') - Grand Atma Hotel</title>
		@include('style')
    </head>
    <body class="bg-secondary">
    	@include('navbar')
        <div class="container">
        	<div class="row">
                <div class="col-lg-3">
                    <h1 class="my-3 text-light">@yield('header')</h1>
                    <div class="list-group">
                        @yield('menu')
                    </div>
                </div>
                <div class="col-lg-9 my-2">
                    @yield('main')
                </div>
            </div>
		</div>
		{{-- @include('footer') --}}
	</body>
</html>

resources/views/layouts/menu.blade.php
@extends('layouts.menu-frame')

@section('menu')
    <a href="{{ route('user.index') }}" class="list-group-item">User</a>
    <a href="{{ route('facility.index') }}" class="list-group-item">Fasilitas</a>
    <a href="{{ route('room-type.index') }}" class="list-group-item">Jenis Kamar</a>
    <a href="{{ route('room.index') }}" class="list-group-item">Kamar</a>
    <a href="{{ route('reservation.index') }}" class="list-group-item">Reservasi</a>
    <a href="{{ route('season.index') }}" class="list-group-item">Season</a>
    <a href="{{ route('price.index') }}" class="list-group-item">Tarif</a>
    <a href="{{ route('report.index') }}" class="list-group-item">Laporan</a>
@endsection

@section('main')
    @if ($success = Session::get('success'))
        <div class="alert alert-success alert-dismissible fade show my-1" role="alert">
            <h5 class="alert-title">Sukses</h5>
            <div>{{ $success }}</div>
            <button type="button" class="close" data-dismiss="alert" aria-label="Hilangkan">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    @endif
    @if ($errors->any())
        <div class="alert alert-danger alert-dismissible fade show my-1" role="alert">
            <h5 class="alert-title">Gagal</h5>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
            <button type="button" class="close" data-dismiss="alert" aria-label="Hilangkan">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    @endif
    @hasSection('create')
        <a class="btn btn-success my-3" href="@yield('create')"><span class="oi oi-plus" title="oi plus" aria-hidden="true"></span> Tambah @yield('header') Baru</a>
    @endif
    @hasSection('back')
        <a class="btn btn-primary my-3" href="@yield('back')">Kembali</a>
    @endif
    @yield('content')
@endsection

resources/views/layouts/profile.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
	<head>
		<title>{{ config('app.name') }} - @yield('title')</title>
		@include('style')
    </head>
    <body class="bg-dark">
    	@include('navbar')
        <div class="container">
        	<div class="row">
                <div class="col-lg-3">
                    <h1 class="my-3 text-light">Akun Saya</h1>
                    <div class="list-group">
                        <a href="#" class="list-group-item">Profil</a>
                        <a href="#" class="list-group-item">Pemesanan</a>
                        <a href="#" class="list-group-item">History</a>
                    </div>
                </div>
                <div class="col-lg-9 my-2">
                    @if ($success = Session::get('success'))
                        <div class="alert alert-success alert-dismissible fade show my-1" role="alert">
                            <h5 class="alert-title">Sukses</h5>
                            <div>{{ $success }}</div>
                            <button type="button" class="close" data-dismiss="alert" aria-label="Hilangkan">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                    @endif
                    @if ($errors->any())
                        <div class="alert alert-danger alert-dismissible fade show my-1" role="alert">
                            <h5 class="alert-title">Gagal</h5>
                            <ul>
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                            <button type="button" class="close" data-dismiss="alert" aria-label="Hilangkan">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                    @endif
                    @yield('content')
                </div>
            </div>
		</div>
		{{-- @include('footer') --}}
	</body>
</html>

resources/views/layouts/register.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
	<head>
		<title>{{ config('app.name') }} - @yield('title')</title>
		@include('style')
    </head>
    <body background="{{ URL::asset('img/register.jpg') }}">
    	@include('navbar')
        <div class="container">
        	<div class="card @yield('style') mx-auto my-5">
        		<div class="card-header text-center">@yield('card-header')</div>
        		<div class="card-body">@yield('card-body')</div>
        		@hasSection('card-footer')
        		<div class="card-footer">
        			<div class="text-center">
        				@yield('card-footer')
        			</div>
        		</div>
        		@endif
			</div>
		</div>
		{{-- @include('footer') --}}
	</body>
</html>

resources/views/layouts/site.blade.php
<!doctype html>
<html lang="{{ app()->getLocale() }}">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>Grand Atma Hotel</title>
        @include('style')
    </head>
    <body>
    @include('navbar')

    @yield('card-body')
    
    </body>
</html>